src/Entity/Courses.php
<?php

namespace App\Entity;

use App\Repository\CoursesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursesRepository::class)]
class Courses
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $pitch = null;



    #[ORM\Column]
    private ?int $position = null;

    #[ORM\Column(length: 255)]
    private ?string $language = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    /**
     * @var Collection<int, Lessons>
     */
    #[ORM\OneToMany(targetEntity: Lessons::class, mappedBy: 'course')]
    private Collection $lessons;

    #[ORM\Column(nullable: true)]
    private ?int $nb_lessons = null;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getPitch(): ?string
    {
        return $this->pitch;
    }

    public function setPitch(string $pitch): static
    {
        $this->pitch = $pitch;

        return $this;
    }



    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): static
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Lessons>
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lessons $lesson): static
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons->add($lesson);
            $lesson->setCourse($this);
        }

        return $this;
    }

    public function removeLesson(Lessons $lesson): static
    {
        if ($this->lessons->removeElement($lesson)) {
            // set the owning side to null (unless already changed)
            if ($lesson->getCourse() === $this) {
                $lesson->setCourse(null);
            }
        }

        return $this;
    }

    public function getNbLessons(): ?int
    {
        return $this->nb_lessons;
    }

    public function setNbLessons(?int $nb_lessons): static
    {
        $this->nb_lessons = $nb_lessons;

        return $this;
    }
    public function getTotalTime(): string
    {
        return $this->totalTime ?? '00:00:00';
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $avatar = 'nobody.png';

    #[ORM\Column(length: 255, unique: true)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private bool $donor = false;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'user')]
    private Collection $articles;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'user')]
    private Collection $comments;

    /**
     * @var Collection<int, Favorites>
     */
    #[ORM\OneToMany(targetEntity: Favorites::class, mappedBy: 'user')]
    private Collection $favorites;

    /**
     * @var Collection<int, CommentsLessons>
     */
    #[ORM\OneToMany(targetEntity: CommentsLessons::class, mappedBy: 'user')]
    private Collection $commentsLessons;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?int $credits = null;

    /**
     * @var Collection<int, UserLesson>
     */
    #[ORM\OneToMany(targetEntity: UserLesson::class, mappedBy: 'User')]
    private Collection $lesson;

    /**
     * @var Collection<int, UserLesson>
     */
    #[ORM\OneToMany(targetEntity: UserLesson::class, mappedBy: 'user')]
    private Collection $userLessons;

    /**
     * @var Collection<int, ConnectionRegister>
     */
    #[ORM\OneToMany(targetEntity: ConnectionRegister::class, mappedBy: 'user')]
    private Collection $connected_at;

    /**
     * @var Collection<int, ConnectionRegister>
     */
    #[ORM\OneToMany(targetEntity: ConnectionRegister::class, mappedBy: 'user')]
    private Collection $connectionRegisters;

    /**
     * @var Collection<int, PurchaseRegister>
     */
    #[ORM\OneToMany(targetEntity: PurchaseRegister::class, mappedBy: 'user')]
    private Collection $purchaseRegisters;

    #[ORM\Column(nullable: true)]
    private ?bool $isFirstPurchase = null;

    /**
     * @var Collection<int, CreditsPurchaseRegister>
     */
    #[ORM\OneToMany(targetEntity: CreditsPurchaseRegister::class, mappedBy: 'user')]
    private Collection $creditsPurchaseRegisters;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $StripeSessionId = null;

    /**
     * @var Collection<int, UserConnection>
     */
    #[ORM\OneToMany(targetEntity: UserConnection::class, mappedBy: 'user')]
    private Collection $ipAdress;

    /**
     * @var Collection<int, UserConnection>
     */
    #[ORM\OneToMany(targetEntity: UserConnection::class, mappedBy: 'user')]
    private Collection $userConnections;

    /**
     * @var Collection<int, PremiumLessonsAccess>
     */
    #[ORM\OneToMany(targetEntity: PremiumLessonsAccess::class, mappedBy: 'user')]
    private Collection $premiumLessonsAccesses;

    





    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->commentsLessons = new ArrayCollection();
        $this->lesson = new ArrayCollection();
        $this->userLessons = new ArrayCollection();
        $this->connected_at = new ArrayCollection();
        $this->connectionRegisters = new ArrayCollection();
        $this->purchaseRegisters = new ArrayCollection();
        $this->creditsPurchaseRegisters = new ArrayCollection();
        $this->ipAdress = new ArrayCollection();
        $this->userConnections = new ArrayCollection();
        $this->premiumLessonsAccesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getDonor(): ?string
    {
        return $this->donor;
    }

    public function setDonor(bool  $donor): static
    {
        $this->donor = $donor;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Comments $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Comments $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favorites>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorites $favorite): static
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->setUser($this);
        }

        return $this;
    }

    public function removeFavorite(Favorites $favorite): static
    {
        if ($this->favorites->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getUser() === $this) {
                $favorite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentsLessons>
     */
    public function getCommentsLessons(): Collection
    {
        return $this->commentsLessons;
    }

    public function addCommentsLesson(CommentsLessons $commentsLesson): static
    {
        if (!$this->commentsLessons->contains($commentsLesson)) {
            $this->commentsLessons->add($commentsLesson);
            $commentsLesson->setUser($this);
        }

        return $this;
    }

    public function removeCommentsLesson(CommentsLessons $commentsLesson): static
    {
        if ($this->commentsLessons->removeElement($commentsLesson)) {
            // set the owning side to null (unless already changed)
            if ($commentsLesson->getUser() === $this) {
                $commentsLesson->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCredits(): ?int
    {
        return $this->credits;
    }

src/Form/CoursesType.php
<?php

namespace App\Form;

use App\Entity\Courses;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoursesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('language')
            ->add('title')
           
            ->add('is_visible', CheckboxType::class, [
                'required' => false,
                // 'mapped' => false,
            ])
            ->add('logo')
            ->add('pitch')
            ->add('position');
            if ($options['data']->getSlug() !== null ) {
                $builder->add('slug', TextType::class, [
                    'label' => 'Slug',
                    'required' => false,
                ]);
            }
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Courses::class,
        ]);
    }
}

templates/courses/components/card.html.twig
<a href="{{ path ('app_one_course', { slug : course.slug})}}" class="flex flex-col justify-between max-w-sm p-6 duration-500 border border-gray-200 rounded-md shadow gap-y-3 style_{{ course.language|upper }} hover:brightness-105 hover:shadow-lg	">


	<div class="flex items-start justify-between gap-3 mb-3">
		<img src="{{course.logo}}" alt="logo" class="p-1 bg-white rounded-full size-12">
		<h5 class="mb-2 text-2xl font-bold tracking-tight text-center gray-900 text-">{{course.title}}</h5>

	</div>

	<p class="mb-3 font-normal text-gray-700 ">{{course.pitch}}</p>


	{% if course.getNbLessons() > 1   %}
		<p class="flex items-center justify-between w-full p-2 text-sm border rounded-md shadow-lg bg-neutral-400/50 border-neutral-500">
			<span>
				Nb d'articles :
				{{ course.getNbLessons() }}
			</span>
			<span>{{course.totalTime}}</span>
		</p>
	{% elseif course.getNbLessons() == 1   %}
		<p class="p-2 text-sm border rounded-md shadow-lg iw-full bg-neutral-400/50 border-neutral-500">
			Nb d'article :
			{{ course.getNbLessons() }}
		</p>
	{% else %}
		<p class="w-full p-2 text-sm border rounded-md shadow-lg bg-neutral-400/50 border-neutral-500">Préparation en cours.</p>
	{% endif %}

</a>

templates/courses/components/comment_form.html.twig
<h2 class="mx-auto my-4 h2 text-clip">Commentaires</h2>
<form action="{{ path('post_lesson_comment') }}" method="post" class="p-4 customForm ">
	<input type="hidden" name="lesson_id" value="{{lesson.id}}">

	<h3 class="h3 text-col1">Ajoutez un commentaire</h3>
	<label for="comment_text" class="block text-sm font-medium text-col1">Votre pseudo</label>
	{% if app.user %}
		<input type="hidden" name="user_id" value="{{app.user.id }}">
		<input type="text" name="pseudo" value="{{ app.user.pseudo }}" disabled>
	{% else %}
		<input type="text" name="pseudo" id="pseudo" class="block w-full mt-1 form-input" placeholder="Entrez votre pseudo" required>
	{% endif %}

	<div class="mb-4">
		<label for="comment_text" class="block text-sm font-medium text-col1">Votre commentaire</label>
		<textarea name="comment_text" id="comment_text" class="block w-full mt-1 form-textarea" rows="4" required></textarea>
	</div>

	<button type="submit" class="buttonValidation">Envoyer le commentaire</button>
</form>

templates/courses/components/comments.html.twig
{# {{ dump(comments) }} #}

<div class="flex flex-col-reverse w-full gap-y-4">
	{% for comment in comments  %}
		<dif class="flex flex-col w-full p-4 border border-col1 bg-color-reverse rounded-xl">
			{% if comment.user %}
				<div class="flex items-center gap-4">
					<img src="{{ asset('images/avatars/' ~ comment.user.avatar) }}" alt="{{comment.user.pseudo}}" class='rounded-full size-12'>
					<p class='text-gray-300 text-small text-thin'>Commentaire de
						{{comment.user.pseudo|capitalize}}</p>
				</div>
				{# Si l'utilisateur est connecté #}
			{% else %}
				<div class="flex items-center gap-4">
					<img src="{{ asset('images/avatars/nobody.png') }}" alt="avatar" class='rounded-full size-12'>
					<p class='text-gray-300 text-small text-thin'>Commentaire de
						{{comment.author|capitalize}}</p>
				</div>
			{% endif %}
			<p class="text-justify ml-14 text-col1">{{comment.comment}}</p>

			{% if is_granted('ROLE_ADMIN') %}
				<form action="{{ path('delete_comment_lesson', {'id': comment.id}) }}" method="post" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire ?');">

					<input type="hidden" name="type" value="{{lesson.type.type}}">
					<input type="hidden" name="alesson_id" value="{{lesson.id}}">
					<button type="submit" class="text-red-500 hover:text-red-700">🗑️ Supprimer</button>
				</form>
			{% endif %}

		</dif>
	{% endfor %}
</div>

templates/courses/components/lesson-premium-no-purchased.html.twig
<h2 class="w-full text-center h2 text-clip">{{lesson.title}}
</h2>
{# <div class="text-white one_article">{{lesson.text|raw}}
</div> #}
{% include 'components/spacing.html.twig' %}
<div class='flex flex-col p-3 mx-auto border gap-y-6 md:gap-y-7 lg:gap-y-8 w-fit color-shadow-md rounded-xl md:p-3 lg:p-4 bg-color-reverse text-col1 border-col1'>
	<div class="flex items-center justify-center gap-5">
		<i class=" fa-solid fa-lock text-col2 fa-2xl scale[1.5]"></i>
		<h3 class=" h3 text-col2">
			L'accés à ce cours est limité.</h3>
	</div>
	<h4 class="mx-auto text-justify h4 text-col1">Afin de soutenir la création, ce contenu est de type Premium</h4>

	{% if  lesson.price == 0  %}
		<div class=" flexMid">
			<form action="{{ path('app_account_purchase_lesson') }}" method="POST">
				<input type="hidden" name="lesson_id" value="{{ lesson.id }}">
				<input type="hidden" name="_token" value="{{ csrf_token('purchase_lesson') }}">
				<button type="submit" class="px-4 buttonValidation w-fit">
					Votre Compagnon de Code vous offre cette leçon 😍 !
					<br>
					Vous pouvez y accéder GRATUITEMENT en cliquant ici.
				</button>
			</form>
		</div>
	{% else %}
		<div class=" flexMid">
			<form action="{{ path('app_account_purchase_lesson') }}" method="POST">
				<input type="hidden" name="lesson_id" value="{{ lesson.id }}">
				<input type="hidden" name="_token" value="{{ csrf_token('purchase_lesson') }}">
				<button type="submit" class="px-4 buttonValidation w-fit">
					Acheter cette leçon pour
					{{ lesson.price }}
					crédits
				</button>
			</form>
		</div>
	{% endif %}

	{% if app.user.credits <=0 %}
		<h4 class="mx-auto h4 text-col1">
			Vous ne possédez pas de crédit actuellement 😱
		</h4>
	{% else %}
		<h4 class="mx-auto h4 text-col1">
			Vous possédez actuellement
			<span class="{{ lesson.price > app.user.credits ? 'text-red-500' : 'text-col2' }}">{{ app.user.credits }}
				crédit{{ app.user.credits != 1 ? 's' : '' }}</span>.
		</h4>
	{% endif %}
	<div class="flexMid">
		<a href="{{ path('app_account_buy_credits')}}">
			<button class="px-4 buttonValidation w-fit">
				<p class="p">Acheter des Crédits.</p>
			</button>
		</a>
	</div>
</div>
{% include 'components/spacing.html.twig' %}

templates/courses/components/lesson-premium-unconnected.html.twig
<h2 class="w-full text-center h2 text-clip">{{lesson.title}} </h2>
{# <div class="text-white one_article">{{lesson.text|raw}}
</div> #}
{% include 'components/spacing.html.twig' %}
<div class='flex flex-col p-3 mx-auto border gap-y-6 md:gap-y-7 lg:gap-y-8 w-fit color-shadow-md rounded-xl md:p-3 lg:p-4 bg-color-reverse text-col1 border-col1'>
	<div class="flex items-center justify-center gap-x-5">
		<i class=" fa-solid fa-lock text-col2 fa-2xl scale[1.5]"></i>
		<h3 class=" h3 text-col2">
			L'accés à ce cours est limité.</h3>
	</div>
	<h4 class="mx-auto text-justify h4 text-col1">Vous devez vous connecter et avoir validé votre accés à ce cours</h4>
	
	<div class="flexMid">
		<a href="{{ path('app_login')}}" >
			<button class="px-4 buttonValidation w-fit"><p class="p">Je me connecte</p></button>
		</a>
	</div>
</div>


{% include 'components/spacing.html.twig' %}

templates/courses/components/lesson.html.twig
{# <h2 class="w-full text-center h2 text-clip">{{lesson.title}}</h2> #}
<div class="text-white one_article">{{lesson.text|raw}}
</div>

<p class="mt-5 text-sm text-gray-500 p ">Écrit en {{ lesson.createdAt|date('m/y') }} par Christophe C.</p>
 {% if  lesson.updatedAt %}
<p class="text-sm text-gray-500 p ">Mis à jour en {{ lesson.updatedAt|date('m/y') }}</p>
 {% endif %}

templates/courses/components/lessonsTitles.html.twig
<h3 class="underline lg:mx-auto h3 text-col2 ">Leçons :</h3>

{% for lesson in lessons  %}
	{% if  lesson.isVisible ==1 %}
		<a href="{{ path('app_one_course', { slug: course.slug , position: lesson.position}) }}" class="flex flex-col gap-x-2 p-2 duration-300 rounded-xl hover:text-col2 {{ lesson.isPremium ? 'text-amber-500' : 'text-col1' }} ">
			<div class="flex items-center w-full lg:justify-between flex-nowrap">
				<div class="flex items-center gap-2">
					{% if lesson.type.type is same as "notion"  %}
						<i class="fa-solid fa-book-open"></i>
					{% elseif lesson.type.type is same as "express" %}
						<i class="fa-solid fa-truck-fast"></i>
					{% elseif lesson.type.type is same as "exercice" %}
						<i class="fa-solid fa-screwdriver-wrench"></i>
					{% elseif lesson.type.type is same as "projet" %}
						<i class="fa-solid fa-rocket"></i>
					{% endif %}
					<p class="p">{{ lesson.title }}</p>
				</div>
				{% if lesson.isPremium  %}
					<i class="max-lg:ml-4 fa-solid fa-crown"></i>
				{% endif %}
			</div>
			<p class="flex items-start text-gray-500 -translate-y-1 text-small">
				{% if lesson.time|date('H') == '00' %}
					{{ lesson.time|date('i:s') }}
				{% else %}
					{{ lesson.time|date('H:i:s') }}
				{% endif %}
			</p>

		</a>
	{% endif %}
{% endfor %}
<div class="flex flex-col mt-4 mb-3 border-t lg:mt-auto border-col1 text-col1">
	<h5 class="my-3 h5">Notice</h5>
	<p>
		<i class="fa-solid fa-book-open"></i>
		=> leçons</p>

	<p>
		<i class="fa-solid fa-truck-fast"></i>
		=> express</p>
	<p>
		<i class="fa-solid fa-screwdriver-wrench"></i>
		=> exercices
	</p>
	<p>
		<i class="fa-solid fa-rocket"></i>
		=> projets
	</p>
</div>